---
version: '3.9'
services:
  webserver-net:
    image: hello-world
    ports:
      - target: 80
        published: 8083
        protocol: tcp
        mode: host
    networks:
      - webserver-net  
networks:
  webserver-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24


